name: WorkFlow for LinkedIn script

on:
  push:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Execute Python script
        env:
          PATH: /usr/bin/google-chrome:$PATH
        run: python linkedin.py
